### ISSUE TITLE
Project status / name takeover?

### ISSUE THREAD

**Issue by baszalmstra** [lain-dono/pixi#1]
Hey @lain-dono !

Im working on a project also called [`pixi`](https://github.com/prefix-dev/pixi). I wanted to publish that to crates.io but your project already uses the name. I noticed that there is only one version and the project hasn't been active for 3 years.

I was wondering if perhaps you would be open to relinquishing the name to us so we can publish our project under the `pixi` name. I would totally understand if this is not something you want to do but I guess it can't hurt to ask. :)

Feel free to reach out over email if you wanna discuss how!

**Comment by lain-dono** [comment]
Sounds reasonable. The project is really abandoned. Transferred ownership.

In case you're wondering, it was originally supposed to be something like a Rust version of [PixiJS](https://github.com/pixijs/pixijs). Right now I think it's better to focus on [bevy](https://github.com/bevyengine/bevy).

**Comment by baszalmstra** [comment]
@lain-dono Thank you very much! I really appreciate it! :)
